<h1>All Tickets</h1>

<p><a href="/ticket/new">Add new ticket</a></p>

<table class="pure-table">
    <tr>
        <th>Title</th>
        <th>Component</th>
        <th>Description</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($tickets as $ticket): ?>

    <tr>
        <td><?=$ticket['Title']?></td>
        <td><?=$ticket['Component']?></td>
        <td><?=$ticket['Description']?> ...</td>
        <td>

        </td>
    </tr>

    <?php endforeach; ?>
</table>